services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - author=wittiden
      - project=BelAgroOptimization
      - version=1.1
    image: bel_agro_app:2.1
    container_name: bel_agro_app
    networks:
      - network
    restart: no
    env_file:
      - .env
    volumes:
      - ./plots:/app/plots
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt

  migrations:
    build:
      context: .
    command: ["alembic", "upgrade", "head"]
    image: bel_agro_migrations:1.0
    container_name: bel_agro_migrations
    networks:
      - network
    restart: no
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrations

  db:
    image: postgres:16-alpine
    container_name: bel_agro_db
    networks:
      - network
    ports:
      - "${DB_PORT_EX}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - db_volume:/var/lib/postgresql/data
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: bel_agro_pgadmin
    networks:
      - network
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:80/misc/ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - pgadmin


networks:
  network:
    driver: bridge
    name: bel_agro_network


volumes:
  db_volume:
    name: bel_agro_db_volume
  pgadmin_volume:
    name: bel_agro_pgadmin_volume
