"""new_tables_view

Revision ID: dc59ec0c06df
Revises: cb603f48d6e1
Create Date: 2026-05-11 15:33:41.146449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc59ec0c06df'
down_revision: Union[str, Sequence[str], None] = 'cb603f48d6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('crops', 'name_ru')
    op.drop_column('crops', 'name_en')
    op.alter_column('scenarios', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('crops', sa.Column('name_en', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('name_ru', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('crops', 'name')
    # ### end Alembic commands ###
