"""create_tables

Revision ID: cb603f48d6e1
Revises: 
Create Date: 2026-05-11 11:28:24.650938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb603f48d6e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('is_fallow', sa.Boolean(), nullable=False),
    sa.Column('sowing_months', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('harvest_months', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('vegetation_days', sa.Integer(), nullable=True),
    sa.Column('rotation_gap_years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('crop_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_crop_code', 'crops', ['code'], unique=False)
    op.create_index('idx_crop_permanent', 'crops', ['is_permanent'], unique=False)
    op.create_table('fields',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('area_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('soil_fertility', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('field_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_field_code', 'fields', ['code'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('crop_data',
    sa.Column('crop_data_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('base_yield_tha', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('price_byn_per_ts', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cost_byn_per_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('seed_cost_byn_per_ha', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_area_pct', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_fert_kg', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fert_cost_byn_per_kg', sa.DECIMAL(precision=8, scale=3), nullable=False),
    sa.Column('fert_response', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('optimal_temp', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('temp_sensitivity', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('water_requirement_mm', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.crop_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('crop_data_id'),
    sa.UniqueConstraint('scenario_id', 'crop_id', name='uk_scenario_crop')
    )
    op.create_index('idx_crop_data_crop', 'crop_data', ['crop_id'], unique=False)
    op.create_index('idx_crop_data_scenario', 'crop_data', ['scenario_id'], unique=False)
    op.create_table('feed_data',
    sa.Column('feed_data_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('price_byn_per_centner', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('cow_need', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('cattle_need', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('pig_need', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('cow_max', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('cattle_max', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('pig_max', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('milk_efficiency', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('beef_efficiency', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('pork_efficiency', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('diminishing_beta', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('available_months', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('winter_price_multiplier', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('summer_price_multiplier', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('feed_data_id'),
    sa.UniqueConstraint('scenario_id', 'feed_type', name='uk_scenario_feed')
    )
    op.create_index('idx_feed_scenario', 'feed_data', ['scenario_id'], unique=False)
    op.create_index('idx_feed_type', 'feed_data', ['feed_type'], unique=False)
    op.create_table('feed_outputs',
    sa.Column('feed_output_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('output_ratio', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.crop_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('feed_output_id'),
    sa.UniqueConstraint('scenario_id', 'crop_id', 'feed_type', name='uk_scenario_crop_feed')
    )
    op.create_index('idx_feed_output_crop', 'feed_outputs', ['crop_id'], unique=False)
    op.create_index('idx_feed_output_scenario', 'feed_outputs', ['scenario_id'], unique=False)
    op.create_table('field_data',
    sa.Column('field_data_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('area_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('field_data_id'),
    sa.UniqueConstraint('scenario_id', 'field_id', name='uk_scenario_field')
    )
    op.create_index('idx_field_data_field', 'field_data', ['field_id'], unique=False)
    op.create_index('idx_field_data_scenario', 'field_data', ['scenario_id'], unique=False)
    op.create_table('livestock_data',
    sa.Column('livestock_data_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('min_heads', sa.Integer(), nullable=False),
    sa.Column('max_heads', sa.Integer(), nullable=False),
    sa.Column('base_yield_kg', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('max_yield_kg', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('price_byn_per_kg', sa.DECIMAL(precision=8, scale=3), nullable=False),
    sa.Column('cost_summer_byn', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cost_winter_byn', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('energy_cost_winter_byn', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('livestock_data_id'),
    sa.UniqueConstraint('scenario_id', 'animal_type', name='uk_scenario_animal')
    )
    op.create_index('idx_livestock_scenario', 'livestock_data', ['scenario_id'], unique=False)
    op.create_index('idx_livestock_type', 'livestock_data', ['animal_type'], unique=False)
    op.create_table('optimization_results',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('total_profit_byn', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('solution_time_sec', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('idx_result_created', 'optimization_results', ['created_at'], unique=False)
    op.create_index('idx_result_scenario', 'optimization_results', ['scenario_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('weather_data_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('temperature_avg', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('rainfall_mm', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('weather_data_id'),
    sa.UniqueConstraint('scenario_id', 'year', 'month', name='uk_scenario_year_month')
    )
    op.create_index('idx_weather_scenario', 'weather_data', ['scenario_id'], unique=False)
    op.create_index('idx_weather_year_month', 'weather_data', ['year', 'month'], unique=False)
    op.create_table('crop_allocations',
    sa.Column('crop_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(length=50), nullable=False),
    sa.Column('crop_code', sa.String(length=50), nullable=False),
    sa.Column('area_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('yield_ts', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fert_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.result_id'], ),
    sa.PrimaryKeyConstraint('crop_allocation_id')
    )
    op.create_index('idx_crop_alloc_result', 'crop_allocations', ['result_id'], unique=False)
    op.create_index('idx_result_crop', 'crop_allocations', ['result_id', 'year', 'field_code', 'crop_code'], unique=False)
    op.create_table('feed_allocations',
    sa.Column('feed_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('produced', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('surplus', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.result_id'], ),
    sa.PrimaryKeyConstraint('feed_allocation_id')
    )
    op.create_index('idx_feed_alloc_result', 'feed_allocations', ['result_id'], unique=False)
    op.create_index('idx_result_feed', 'feed_allocations', ['result_id', 'year', 'feed_type'], unique=False)
    op.create_table('livestock_allocations',
    sa.Column('livestock_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('heads', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('milk_yield_summer_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('milk_yield_winter_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.result_id'], ),
    sa.PrimaryKeyConstraint('livestock_allocation_id')
    )
    op.create_index('idx_livestock_alloc_result', 'livestock_allocations', ['result_id'], unique=False)
    op.create_index('idx_result_livestock', 'livestock_allocations', ['result_id', 'year', 'animal_type'], unique=False)
    op.create_table('monthly_operations',
    sa.Column('monthly_operation_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('sowing_area_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('harvesting_area_ha', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tractor_hours', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('labor_hours', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('silage_consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('hay_consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('concentrate_consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('pasture_consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.result_id'], ),
    sa.PrimaryKeyConstraint('monthly_operation_id')
    )
    op.create_index('idx_monthly_ops_result', 'monthly_operations', ['result_id'], unique=False)
    op.create_index('idx_result_month', 'monthly_operations', ['result_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_result_month', table_name='monthly_operations')
    op.drop_index('idx_monthly_ops_result', table_name='monthly_operations')
    op.drop_table('monthly_operations')
    op.drop_index('idx_result_livestock', table_name='livestock_allocations')
    op.drop_index('idx_livestock_alloc_result', table_name='livestock_allocations')
    op.drop_table('livestock_allocations')
    op.drop_index('idx_result_feed', table_name='feed_allocations')
    op.drop_index('idx_feed_alloc_result', table_name='feed_allocations')
    op.drop_table('feed_allocations')
    op.drop_index('idx_result_crop', table_name='crop_allocations')
    op.drop_index('idx_crop_alloc_result', table_name='crop_allocations')
    op.drop_table('crop_allocations')
    op.drop_index('idx_weather_year_month', table_name='weather_data')
    op.drop_index('idx_weather_scenario', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index('idx_result_scenario', table_name='optimization_results')
    op.drop_index('idx_result_created', table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index('idx_livestock_type', table_name='livestock_data')
    op.drop_index('idx_livestock_scenario', table_name='livestock_data')
    op.drop_table('livestock_data')
    op.drop_index('idx_field_data_scenario', table_name='field_data')
    op.drop_index('idx_field_data_field', table_name='field_data')
    op.drop_table('field_data')
    op.drop_index('idx_feed_output_scenario', table_name='feed_outputs')
    op.drop_index('idx_feed_output_crop', table_name='feed_outputs')
    op.drop_table('feed_outputs')
    op.drop_index('idx_feed_type', table_name='feed_data')
    op.drop_index('idx_feed_scenario', table_name='feed_data')
    op.drop_table('feed_data')
    op.drop_index('idx_crop_data_scenario', table_name='crop_data')
    op.drop_index('idx_crop_data_crop', table_name='crop_data')
    op.drop_table('crop_data')
    op.drop_table('scenarios')
    op.drop_index('idx_field_code', table_name='fields')
    op.drop_table('fields')
    op.drop_index('idx_crop_permanent', table_name='crops')
    op.drop_index('idx_crop_code', table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
